/*
 * Copyright (c) 2026 Hardik Bhaskar
 * Licensed under the MIT License.
 *
 * boot.rs — Declarative Boot Configuration Generator & Atomic Boot State.
 *          Generates validated limine.conf configurations as a pure function of the
 *          GenerationRegistry. Enforces kernel panic=10 automated reboot parameters,
 *          read-only rootfs mounts, candidate boot trial tags, and hardware watchdog probing.
 */

use crate::error::ControlError;
use crate::state::{atomic_write_file, GenerationRegistry, GenerationStatus};
use serde::{Deserialize, Serialize};
use std::path::Path;

pub const DEFAULT_LIMINE_CONF_PATH: &str = "/boot/efi/limine.conf";
pub const DEFAULT_KERNEL_PATH: &str = "boot():/vmlinuz-mahina";
pub const DEFAULT_INITRAMFS_PATH: &str = "boot():/initramfs-mahina.img";
pub const DEFAULT_BOOT_TIMEOUT_SECS: u32 = 3;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct RecoveryCapabilities {
    pub kernel_panic_reboot: bool,
    pub hardware_watchdog: bool,
    pub boot_counter_rollback: bool,
}

impl RecoveryCapabilities {
    pub fn probe() -> Self {
        let watchdog_present = Path::new("/dev/watchdog").exists();
        Self {
            kernel_panic_reboot: true, // Ensured via panic=10 in cmdline
            hardware_watchdog: watchdog_present,
            boot_counter_rollback: true, // Ensured via transactional boot-state
        }
    }

    pub fn display_summary(&self) -> String {
        format!(
            "Recovery Capabilities:\n\
             [{}] Kernel Panic Reboot (panic=10 panic_on_oops=1)\n\
             [{}] Hardware/Virtual Watchdog ({})\n\
             [{}] Transactional Boot Counter & Rollback (max 3 attempts)",
            if self.kernel_panic_reboot { "✓" } else { " " },
            if self.hardware_watchdog { "✓" } else { " " },
            if self.hardware_watchdog { "/dev/watchdog active" } else { "unavailable" },
            if self.boot_counter_rollback { "✓" } else { " " }
        )
    }
}

#[derive(Debug, Clone)]
pub struct LimineConfigGenerator {
    kernel_path: String,
    initramfs_path: String,
    timeout_secs: u32,
}

impl Default for LimineConfigGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl LimineConfigGenerator {
    pub fn new() -> Self {
        Self {
            kernel_path: DEFAULT_KERNEL_PATH.to_string(),
            initramfs_path: DEFAULT_INITRAMFS_PATH.to_string(),
            timeout_secs: DEFAULT_BOOT_TIMEOUT_SECS,
        }
    }

    pub fn with_paths(kernel: impl Into<String>, initramfs: impl Into<String>) -> Self {
        Self {
            kernel_path: kernel.into(),
            initramfs_path: initramfs.into(),
            timeout_secs: DEFAULT_BOOT_TIMEOUT_SECS,
        }
    }

    pub fn with_timeout(mut self, timeout: u32) -> Self {
        self.timeout_secs = timeout;
        self
    }

    /// Pure function generating the complete `limine.conf` string from the registry.
    ///
    /// Invariants:
    /// 1. Default entry is Entry 1 (Candidate if provided, or current healthy).
    /// 2. Candidate entry strictly injects `mahina.candidate=1` and `panic=10 panic_on_oops=1`.
    /// 3. Rootfs is mounted read-only: `rootflags=ro,subvol=@generations/<id>/rootfs`.
    /// 4. The designated fallback healthy generation is always preserved as secondary choice.
    /// 5. Historical healthy generations are appended as alternatives.
    pub fn generate(&self, registry: &GenerationRegistry, candidate_id: Option<u32>) -> String {
        let mut out = String::new();

        out.push_str("# MahinaOS Bootloader Configuration\n");
        out.push_str("# Automatically generated by mahina-control-d — DO NOT HAND EDIT\n");
        out.push_str(&format!("timeout: {}\n\n", self.timeout_secs));

        // 1. If candidate is present, candidate is Entry 1
        if let Some(cand_id) = candidate_id {
            if let Some(cand) = registry.get_summary(cand_id) {
                out.push_str(&format!(
                    "/MahinaOS Gen #{} [CANDIDATE TRIAL - TRIES 3]\n\
                     \tprotocol: linux\n\
                     \tpath: {}\n\
                     \tmodule_path: {}\n\
                     \tcmdline: root=LABEL=MAHINA_ROOT rootflags=ro,subvol=@generations/{}/rootfs console=tty0 console=ttyS0 mahina.generation={} mahina.candidate=1 panic=10 panic_on_oops=1\n\n",
                    cand.id, self.kernel_path, self.initramfs_path, cand.id, cand.id
                ));
            }
        }

        // 2. Active Current Healthy Generation (or Fallback if Candidate is Entry 1)
        let current_id = registry.current_generation_id;
        if candidate_id != Some(current_id) {
            let label = if candidate_id.is_none() {
                format!("MahinaOS Gen #{} [DEFAULT HEALTHY]", current_id)
            } else {
                format!("MahinaOS Gen #{} [CURRENT HEALTHY]", current_id)
            };

            out.push_str(&format!(
                "/{}\n\
                 \tprotocol: linux\n\
                 \tpath: {}\n\
                 \tmodule_path: {}\n\
                 \tcmdline: root=LABEL=MAHINA_ROOT rootflags=ro,subvol=@generations/{}/rootfs console=tty0 console=ttyS0 mahina.generation={} panic=10\n\n",
                label, self.kernel_path, self.initramfs_path, current_id, current_id
            ));
        }

        // 3. Fallback Healthy Generation (if different from Current and Candidate)
        let fallback_id = registry.fallback_generation_id;
        if fallback_id != current_id && candidate_id != Some(fallback_id) {
            out.push_str(&format!(
                "/MahinaOS Gen #{} [FALLBACK HEALTHY]\n\
                 \tprotocol: linux\n\
                 \tpath: {}\n\
                 \tmodule_path: {}\n\
                 \tcmdline: root=LABEL=MAHINA_ROOT rootflags=ro,subvol=@generations/{}/rootfs console=tty0 console=ttyS0 mahina.generation={} panic=10\n\n",
                fallback_id, self.kernel_path, self.initramfs_path, fallback_id, fallback_id
            ));
        }

        // 4. Other retained healthy or superseded generations
        for g in &registry.generations {
            if g.id == current_id || g.id == fallback_id || candidate_id == Some(g.id) {
                continue;
            }
            if g.status == GenerationStatus::Healthy || g.status == GenerationStatus::Superseded {
                let badge = if g.is_pinned { "[PINNED]" } else { "[BACKUP]" };
                out.push_str(&format!(
                    "/MahinaOS Gen #{} {}\n\
                     \tprotocol: linux\n\
                     \tpath: {}\n\
                     \tmodule_path: {}\n\
                     \tcmdline: root=LABEL=MAHINA_ROOT rootflags=ro,subvol=@generations/{}/rootfs console=tty0 console=ttyS0 mahina.generation={} panic=10\n\n",
                    g.id, badge, self.kernel_path, self.initramfs_path, g.id, g.id
                ));
            }
        }

        out
    }

    /// Atomically write the generated configuration to target path.
    pub fn write_atomic(&self, target_path: &Path, content: &str) -> Result<(), ControlError> {
        atomic_write_file(target_path, content.as_bytes())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::state::GenerationSummary;

    #[test]
    fn test_limine_config_generator_with_candidate() {
        let mut reg = GenerationRegistry::baseline();
        reg.generations.push(GenerationSummary {
            id: 102,
            parent_id: Some(101),
            description: "Test Candidate".to_string(),
            created_at_epoch_secs: 2000,
            status: GenerationStatus::Candidate,
            is_pinned: false,
            is_current: false,
            is_fallback: false,
        });

        let gen = LimineConfigGenerator::new();
        let conf = gen.generate(&reg, Some(102));

        // Invariants check:
        // 1. Candidate is top entry
        assert!(conf.contains("/MahinaOS Gen #102 [CANDIDATE TRIAL - TRIES 3]"));
        // 2. Contains panic=10 and candidate tag
        assert!(conf.contains("mahina.candidate=1 panic=10 panic_on_oops=1"));
        // 3. Fallback Gen 101 is preserved
        assert!(conf.contains("/MahinaOS Gen #101 [CURRENT HEALTHY]") || conf.contains("/MahinaOS Gen #101"));
        assert!(conf.contains("rootflags=ro,subvol=@generations/101/rootfs"));
    }

    #[test]
    fn test_limine_config_generator_without_candidate() {
        let reg = GenerationRegistry::baseline();
        let gen = LimineConfigGenerator::new();
        let conf = gen.generate(&reg, None);

        // Current healthy is default entry
        assert!(conf.contains("/MahinaOS Gen #101 [DEFAULT HEALTHY]"));
        assert!(!conf.contains("mahina.candidate=1"));
        assert!(conf.contains("rootflags=ro,subvol=@generations/101/rootfs"));
    }

    #[test]
    fn test_recovery_capabilities_summary() {
        let caps = RecoveryCapabilities {
            kernel_panic_reboot: true,
            hardware_watchdog: false,
            boot_counter_rollback: true,
        };
        let summary = caps.display_summary();
        assert!(summary.contains("[✓] Kernel Panic Reboot"));
        assert!(summary.contains("[ ] Hardware/Virtual Watchdog"));
        assert!(summary.contains("[✓] Transactional Boot Counter & Rollback"));
    }
}
