TIMEOUT=5
timeout: 5

:Mahina OS (Limine 5)
PROTOCOL=linux
KERNEL_PATH=boot:///vmlinuz-mahina
MODULE_PATH=boot:///initramfs-mahina.img
KERNEL_CMDLINE=console=tty0 console=ttyS0 loglevel=7 video=1024x768

/Mahina OS (Limine 7)
    protocol: linux
    kernel_path: boot():/vmlinuz-mahina
    module_path: boot():/initramfs-mahina.img
    cmdline: console=tty0 console=ttyS0 loglevel=7 video=1024x768

/Mahina OS (Limine 8)
    protocol: linux
    path: boot():/vmlinuz-mahina
    module_path: boot():/initramfs-mahina.img
    cmdline: console=tty0 console=ttyS0 loglevel=7 video=1024x768
